### ISSUE TITLE
Ensure relative URLs

### ISSUE THREAD

**Issue by kmaasrud** [mdzk-rs/mdbook-wikilink#5]
Some scenarios, like hosting in sub-directories, need relative links in order to work correctly.

**Comment by ratsclub** [comment]
I don't use relative URLs, but does this option work for this?

https://rust-lang.github.io/mdBook/format/configuration/renderers.html?highlight=site-url#configuring-renderers

**Comment by kmaasrud** [comment]
> I don't use relative URLs, but does this option work for this?

Not really, no... I think this mainly affects the links in the sidebar. Our preprocessor followed by the HtmlHandlebars renderer seems to be converting `[[note]]` into `<a href="/note">note<a>`. That forward slash means we link to `note` directly from the domain, which means subdirectory hosting does not work.

In the above scenario, we would like `<a href="note">note<a>` and correspondingly relative if we are linking into/out of a note folder.

**Comment by ratsclub** [comment]
I mean, can't we just append this option to the string?

**Comment by kmaasrud** [comment]
I actually think it's as simple as changing this

https://github.com/mdzk-rs/mdbook-wikilink/blob/d71fa814819df450e4dcfee065f5feeaa0f061ad/src/lib.rs#L81

into `format!("[{}](<{}.md>)", title, link)`.

That would probably fix the sub-directory issue, but there's still a case to be made for how wikilinks are resolved. Do they need to specify the exact relative path, or is it enough that they are unique, like in Obsidian?

**Comment by ratsclub** [comment]
This would break my workflow as Obsidian keeps an index of notes... We have this problem with `mdbook-backlinks` too since the navigation will start its path with the current note.

**Comment by NOBLES5E** [comment]
mdbook actually complains about this:

```
warning: Absolute link should be made relative
  ┌─ programming/design-patterns/index.md:5:3
  │
5 │ * [visitor-pattern](</programming/design-patterns/visitor-pattern.md>): Generic Functions (Multiple Dispatch)
  │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Absolute link should be made relative
  │
  = When viewing a document directly from the file system and click on an
    absolute link (e.g. `/index.md`), the browser will try to navigate to
    `/index.md` on the current file system (i.e. the `index.md` file inside
    `/` or `C:\`) instead of the `index.md` file at book's base directory as
    intended.

    This warning helps avoid the situation where everything will seem to work
    fine when viewed using a web server (e.g. GitHub Pages or `mdbook serve`),
    but users viewing the book from the file system may encounter broken links.

    To ignore this warning, you can edit `book.toml` and set the warning policy to
    "ignore".

        [output.linkcheck]
        warning-policy = "ignore"

    For more details, see https://github.com/Michael-F-Bryan/mdbook-linkcheck/issues/33
  = Suggestion: change the link to "visitor-pattern.md"
```
